language: java
jdk:
- oraclejdk8
branches:
  only:
  - master
notifications:
  email:
    recipients:
    - rp.orbezo@alumnos.urjc.com
script:
- mvn verify
- mvn org.jacoco:jacoco-maven-plugin:prepare-agent verify
- mvn sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=ropili19-github -Dsonar.login=$SONAR
